name: Django CI

on:
  push:
    branches:
      - main  # Ejecutar cuando haya cambios en la rama principal
  pull_request:
    branches:
      - main  # Ejecutar cuando se cree un PR para la rama principal

jobs:
  test:
    runs-on: ubuntu-latest  # Usar Ubuntu para ejecutar el flujo de trabajo

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Clona el código del repositorio

    - name: Set up Python
      uses: actions/setup-python@v2  # Configura Python
      with:
        python-version: '3.8'  # Usa la versión de Python que prefieras

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Actualiza pip
        pip install -r requirements.txt  # Instala las dependencias desde requirements.txt

    - name: Run tests for core app
      run: |
        python manage.py test core  # Ejecuta los tests de la app 'core'

    - name: Run tests for services app
      run: |
        python manage.py test services  # Ejecuta los tests de la app 'services'

    - name: Run tests for blog app
      run: |
        python manage.py test blog  # Ejecuta los tests de la app 'blog'